# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Log_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('package_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Log_web.Login_user')),
            ],
        ),
        migrations.CreateModel(
            name='Package_recieve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr_pro', models.CharField(max_length=20)),
                ('addr_city', models.CharField(blank=True, max_length=20)),
                ('addr_district', models.CharField(max_length=20)),
                ('addr_block', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=20)),
                ('package_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Log_web.Package')),
            ],
        ),
        migrations.CreateModel(
            name='Package_send',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr_pro', models.CharField(max_length=20)),
                ('addr_city', models.CharField(blank=True, max_length=20)),
                ('addr_district', models.CharField(max_length=20)),
                ('addr_block', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=20)),
                ('package_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Log_web.Package')),
            ],
        ),
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('addr_pro', models.CharField(max_length=20)),
                ('addr_city', models.CharField(blank=True, max_length=20)),
                ('addr_district', models.CharField(max_length=20)),
                ('addr_block', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=20)),
            ],
        ),
    ]
