# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Log_web', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.RemoveField(
            model_name='distributor',
            name='distributor',
        ),
        migrations.RemoveField(
            model_name='distributor',
            name='godown',
        ),
        migrations.RemoveField(
            model_name='godown_staff',
            name='godown',
        ),
        migrations.RemoveField(
            model_name='godown_staff',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='package',
            name='username',
        ),
        migrations.RemoveField(
            model_name='package_info',
            name='godown_id',
        ),
        migrations.RemoveField(
            model_name='package_info',
            name='package_id',
        ),
        migrations.RemoveField(
            model_name='package_receive',
            name='package_id',
        ),
        migrations.RemoveField(
            model_name='package_send',
            name='package_id',
        ),
        migrations.DeleteModel(
            name='User_info',
        ),
        migrations.DeleteModel(
            name='Distributor',
        ),
        migrations.DeleteModel(
            name='Godown',
        ),
        migrations.DeleteModel(
            name='Godown_staff',
        ),
        migrations.DeleteModel(
            name='Login_user',
        ),
        migrations.DeleteModel(
            name='Package',
        ),
        migrations.DeleteModel(
            name='Package_info',
        ),
        migrations.DeleteModel(
            name='Package_receive',
        ),
        migrations.DeleteModel(
            name='Package_send',
        ),
    ]
