# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-23 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Log_web', '0002_package_package_recieve_package_send_user_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Godown',
            fields=[
                ('godown_id', models.AutoField(primary_key=True, serialize=False)),
                ('godown_num', models.IntegerField()),
                ('addr_pro', models.CharField(max_length=20)),
                ('addr_city', models.CharField(blank=True, max_length=20)),
                ('addr_district', models.CharField(max_length=20)),
                ('addr_block', models.CharField(max_length=100)),
            ],
        ),
    ]
