# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Log_web', '0003_auto_20180102_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package_info',
            name='Distributor_id_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
