# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-24 08:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Log_web', '0004_company_distributor_distributor_package_godown_staff_package_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package_info',
            name='loaction',
        ),
        migrations.AddField(
            model_name='package_info',
            name='godown_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Log_web.Godown'),
        ),
    ]
