# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-24 08:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Log_web', '0005_auto_20171224_0818'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Package_recieve',
            new_name='Package_receive',
        ),
    ]
