# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-24 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Log_web', '0006_auto_20171224_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package_info',
            name='transport_form',
            field=models.CharField(max_length=10),
        ),
    ]
