# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Log_web', '0007_auto_20171224_0914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_info',
            old_name='user_id',
            new_name='user_name',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='username',
        ),
        migrations.AlterField(
            model_name='user_info',
            name='addr_block',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='addr_district',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='addr_pro',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='tel',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
