# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Log_web', '0011_auto_20171228_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sum_money', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Distributor_package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Log_web.Distributor')),
            ],
        ),
        migrations.CreateModel(
            name='Godown',
            fields=[
                ('godown_id', models.AutoField(primary_key=True, serialize=False)),
                ('godown_num', models.IntegerField()),
                ('addr_pro', models.CharField(max_length=20)),
                ('addr_city', models.CharField(blank=True, max_length=20)),
                ('addr_district', models.CharField(max_length=20)),
                ('addr_block', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Godown_staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('godown', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Log_web.Godown')),
            ],
        ),
        migrations.CreateModel(
            name='Login_user',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('count_type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('package_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Log_web.Login_user')),
            ],
        ),
        migrations.CreateModel(
            name='Package_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('transport_form', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=100)),
                ('Distributor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Log_web.Distributor')),
                ('godown_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Log_web.Godown')),
                ('package_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Log_web.Package')),
            ],
        ),
        migrations.CreateModel(
            name='Package_receive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr_pro', models.CharField(max_length=20)),
                ('addr_city', models.CharField(blank=True, max_length=20)),
                ('addr_district', models.CharField(max_length=20)),
                ('addr_block', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=20)),
                ('package_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Log_web.Package')),
            ],
        ),
        migrations.CreateModel(
            name='Package_send',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr_pro', models.CharField(max_length=20)),
                ('addr_city', models.CharField(blank=True, max_length=20)),
                ('addr_district', models.CharField(max_length=20)),
                ('addr_block', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=20)),
                ('package_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Log_web.Package')),
            ],
        ),
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('user_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('addr_pro', models.CharField(blank=True, max_length=20)),
                ('addr_city', models.CharField(blank=True, max_length=20)),
                ('addr_district', models.CharField(blank=True, max_length=20)),
                ('addr_block', models.CharField(blank=True, max_length=100)),
                ('tel', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='godown_staff',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Log_web.Login_user'),
        ),
        migrations.AddField(
            model_name='distributor_package',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Log_web.Package'),
        ),
        migrations.AddField(
            model_name='distributor',
            name='distributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Log_web.Login_user'),
        ),
        migrations.AddField(
            model_name='distributor',
            name='godown',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Log_web.Godown'),
        ),
    ]
