# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Log_web', '0013_auto_20171229_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributor_package',
            name='distributor',
        ),
        migrations.RemoveField(
            model_name='distributor_package',
            name='package',
        ),
        migrations.DeleteModel(
            name='Distributor_package',
        ),
    ]
